[[UNRESOLVED_REF]]
id = "MISSING_TWEAKXL"
span_starts_with  = "TweakDBManager"
message = "TweakXL not found. Make sure it is installed properly."

[[UNRESOLVED_TYPE]]
id = "MISSING_TWEAKXL"
file = "VehicleSecurityRework/Vehicle/VehicleExtensions.reds"
line_contains  = "ScriptableTweak"
message = "TweakXL not found. Make sure it is installed properly."

[[UNRESOLVED_METHOD]]
id = "MISSING_TWEAKXL"
file = "VehicleSecurityRework/Vehicle/VehicleExtensions.reds"
line_contains  = "GetFlat"
message = "TweakXL not found. Make sure it is installed properly."

[[UNRESOLVED_TYPE]]
id = "MISSING_CUSTOM_HACKING_SYSTEM"
line_contains  = "CustomHackingSystem"
message = "CustomHackingSystem not found. Make sure the latest version and it's dependencies are correctly installed."