[[UNRESOLVED_TYPE]]
id = "MISSING_CUSTOM_HACKING_SYSTEM"
file = "VehicleSecurityRework/Quickhacks/VehicleDeviceActions.reds"
line_contains  = "CustomHackingSystem"
message = "VehicleSecurityRework depends on CustomHackingSystem but it seems you don't have it installed. Make sure it is installed properly"

[[UNRESOLVED_METHOD]]
id = "MISSING_TWEAKXL"
line_contains  = "TweakDBInterface"
message = "TweakXL mod not found. Try to reinstall it and make sure you have the latest version of the game."

[[UNRESOLVED_METHOD]]
id = "MISSING_TWEAKXL"
line_contains  = "TweakDBManager"
message = "TweakXL mod not found. Try to reinstall it and make sure you have the latest version of the game."

[[UNRESOLVED_REF]]
id = "MISSING_MOD_SETTINGS"
line_contains  = "ModSettings"
message = "ModSettings mod not found. Try to reinstall it and make sure you have the latest version of the game."

[[UNRESOLVED_REF]]
id = "MISSING_ARCHIVE_XL"
line_contains  = "ArchiveXL"
message = "ArchiveXL mod not found. Try to reinstall it and make sure you have the latest version of the game."
